### ISSUE TITLE
Support other docker logging options if json-file not available

### ISSUE THREAD

**Issue by juztas** [sdn-sense/siterm-startup#10]
Podman, docker, docker-ce... 
```
Server:
 Plugins:
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
```
or
```
host:
  arch: ppc64le
  logDriver: k8s-file
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
```
